export const LOGIN_MODAL = 'LOGIN_MODAL';
export const SHARE_MODAL = 'SHARE_MODAL';
export const CONTACT_INFO_MODAL = 'CONTACT_INFO_MODAL';
export const MOBILE_NUMBER_VERIFICATION_MODAL =
  'MOBILE_NUMBER_VERIFICATION_MODAL';
export const CONFIRM_REPORT_MODAL = 'CONFIRM_REPORT_MODAL';
export const SUCCESS_MESSAGE_MODAL = 'SUCCESS_MESSAGE_MODAL';
export const CONFIRM_DELETE_MODAL = 'CONFIRM_DELETE_MODAL';
export const CONFIRM_MOBILE_NUMBER_DELETE_MODAL =
  'CONFIRM_MOBILE_NUMBER_DELETE_MODAL';
export const FEEDBACK_MODAL = 'FEEDBACK_MODAL';
